#!/bin/bash
# Job name
#PBS -N VASP_JOB
# Nodes and processors to run
#PBS -l nodes=3:ppn=16 
# Walltime Format: HH:MM:SS
#PBS -l walltime=24:00:00
# File for standard output
#PBS -o out_$PBS_JOBID.log
# File for error message
#PBS -e out_$PBS_JOBID.err
#PBS -V


############################################################
#       NO CHANGES BELOW THIS LINE
############################################################

# go to work dir
cd $PBS_O_WORKDIR

# Variable Setting
source /public/apps/intel/parallel_studio_xe_2018_u4/impi/2018.4.274/bin64/mpivars.sh intel64

# 5.4.4
# VASP_EXEC=/public/apps/vasp/5.4.4/vasp_5.4.4_gam
# VASP_EXEC=/public/apps/vasp/5.4.4/vasp_5.4.4_soc
# VASP_EXEC=/public/apps/vasp/5.4.4/vasp_5.4.4_ncl
VASP_EXEC=/public/apps/vasp/5.4.4/vasp_5.4.4_std

ln -sf /public/apps/vasp/5.4.4/vdw_kernel.bindat

IB_FLAG="-env I_MPI_FABRICS shm:ofa"
############################################################

# setup Nums of Processor
echo "============================================================"
echo $PBS_NODEFILE
HOSTFILE=${PBS_O_WORKDIR}/.NODES_to_RUN.${PBS_JOBID}
NCPUS=$(cat $PBS_NODEFILE | wc -l)
NNODES=$(cat $PBS_NODEFILE | uniq | wc -l)
uniq -c $PBS_NODEFILE | awk '{printf "%s:%d\n", $2,$1;}' > ${HOSTFILE}
echo "Job name: $PBS_JOBNAME"
echo "Job ID: $PBS_JOBID"
echo "Job submitted to queue: $PBS_QUEUE"
echo "Number of nodes: $NNODES"
echo "Number of processors: $NCPUS"
echo "VASP is running on the following nodes:"
echo 
cat ${HOSTFILE} | sed 's/^/\ \ \ \ /'
echo 
echo "============================================================"
echo

mpirun $IB_FLAG $VASP_EXEC

# [ -s CONTCAR ] && mv CONTCAR POSCAR
rm CHG

# cleaning 
rm ${HOSTFILE}
